apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.service.name }}
  labels:
    app: {{ .Values.label }}-svc
    project: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }} # 수정 필요
spec:
  type: "{{ .Values.service.type }}"
  selector:
    app: {{ .Values.label }}-web
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}
